### ISSUE TITLE
There was a problem with the request

### ISSUE THREAD

**Issue by Anniepoo** [roblaing/checkers-webapp#1]
Played game to this position
notation as per chess, 1 is lowest row, A is leftmost column

red a4, c2,f3,f5
red king d3,d5,f7
black king e2

human plays d3 to f1, takes black king to win

click select of king shows valid moves as normal

clicking blank square to move causes alert to appear with "There was a problem with this request!"

/move Failed to load resource: the server responded with a status of 500 (Internal Server Error)

The select/move sequence can be repeated with same results

Also, you're now featured on the SWI-Prolog news.

**Comment by roblaing** [comment]
Many thanks Anne.
Recognising the game is over instead of sending a response the current code can't handle for some reason is a priority bug I hope to sort out soon.

**Comment by roblaing** [comment]
I've managed to get the scripts to recognise when the game is over and put up an alert box. In due course, players will be offered a new game (for now, player have to press the refresh button on their browser).
